# Generated by Django 5.2 on 2025-05-18 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateField(default=datetime.date(2025, 5, 18)),
        ),
    ]
