# Generated by Django 5.2 on 2025-05-19 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_playlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateField(default=datetime.date(2025, 5, 19)),
        ),
    ]
