# Generated by Django 5.2 on 2025-05-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
