# Generated by Django 5.2 on 2025-06-12 13:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_alter_playlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover_art',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
