# Generated by Django 5.2 on 2025-06-09 19:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
