# Generated by Django 5.2 on 2025-05-16 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='song_covers/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(default=datetime.date(2025, 5, 16)),
        ),
    ]
