# Generated by Django 5.2 on 2025-06-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_alter_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
