# Generated by Django 5.2 on 2025-06-09 19:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_song_play_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_art',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
